### ISSUE TITLE
Receiver permits input from the backside

### ISSUE THREAD

**Issue by stefan-wiebe** [StW96/Kartoffelchips#1]
It's not supposed to.

**Comment by ttimpe** [comment]
No it should not

**Comment by stefan-wiebe** [comment]
Well, blasted.

**Comment by Dede98** [comment]
From my View:  http://puu.sh/k2mfl/7298ed09f5.png
From Tobias View: http://puu.sh/k2mhp/194c55a7a5.png

**Comment by stefan-wiebe** [comment]
Fixed.
