### ISSUE TITLE
Other half of Mirror being drawn when not active

### ISSUE THREAD

**Issue by Dede98** [StW96/Kartoffelchips#5]
http://puu.sh/jYTQ7/fc5f67f8ea.png

**Comment by stefan-wiebe** [comment]
Only happens if the mirror is right in front of the emitter.

**Comment by Dede98** [comment]
And why?!

**Comment by stefan-wiebe** [comment]
If I knew that, I'd fix it immediately. As it is right now, I'd rather 
draw menu icons!

**Comment by StW96** [comment]
If I knew that, I'd fix it immediately. As of right now, I'd rather make menu items!

**Comment by stefan-wiebe** [comment]
Fixed.
