### ISSUE TITLE
Add Help Messages

### ISSUE THREAD

**Issue by stefan-wiebe** [StW96/Kartoffelchips#8]
Implement help messages introducing the player to the gameplay mechanics.

**Comment by ttimpe** [comment]
Basic alert box functionality implemented, available via showAlert('TEXT', 'TITLE', ['Button 1', 'Button 2'].

Still needs work for title, hover, callbacks etc.

**Comment by ttimpe** [comment]
Titles now working, multiline message support added.

**Comment by ttimpe** [comment]
alerts can be thrown now using an array of type Button, a Button has a title and an action.

**Comment by Dede98** [comment]
Button isn't working yet.

**Comment by ttimpe** [comment]
Waiting on #17.

**Comment by Dede98** [comment]
Every thing is Finished until return values.

**Comment by ttimpe** [comment]
Closed for release. Further issues in next ticket.
